2019-07-13 06:42:19,232 - ZHU_SPIDER - ERROR - process error: https://dblp.uni-trier.de/db/journals?pos=01
response: log/error_content/4e2d4ffe-a4f6-11e9-888e-d0817ab669b6_log.txt
Traceback (most recent call last):
  File "/Users/huyiyong/anaconda3/lib/python3.6/site-packages/fetchman/utils/decorator.py", line 42, in wrapper
    for callback in process:
  File "spiderMain1.py", line 38, in process
    soup = BeautifulSoup(response,'html.parser')
NameError: name 'BeautifulSoup' is not defined

2019-07-13 06:42:47,381 - ZHU_SPIDER - ERROR - process error: https://dblp.uni-trier.de/db/journals?pos=01
response: log/error_content/5ef6d206-a4f6-11e9-9562-d0817ab669b6_log.txt
Traceback (most recent call last):
  File "/Users/huyiyong/anaconda3/lib/python3.6/site-packages/fetchman/utils/decorator.py", line 42, in wrapper
    for callback in process:
  File "spiderMain1.py", line 35, in process
    soup = BeautifulSoup(response,'html.parser')
  File "/Users/huyiyong/anaconda3/lib/python3.6/site-packages/bs4/__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'Response' has no len()

